# Generated by Django 5.2.1 on 2025-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField()),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'book_id', 'borrow_date'), name='unique_together_per_day')],
            },
        ),
    ]
